//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotiNet.Entities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MotiNet.Entities.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimistic concurrency failure, object has been modified..
        /// </summary>
        internal static string ConcurrencyFailure {
            get {
                return ResourceManager.GetString("ConcurrencyFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown failure has occured..
        /// </summary>
        internal static string DefaultError {
            get {
                return ResourceManager.GetString("DefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sort expression &apos;{0}&apos;. Property &apos;{1}&apos; not found in &apos;{2}&apos; class..
        /// </summary>
        internal static string InvalidSortProperty {
            get {
                return ResourceManager.GetString("InvalidSortProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement ICodeBasedEntityStore&lt;TEntity&gt;..
        /// </summary>
        internal static string StoreNotICodeBasedEntityStore {
            get {
                return ResourceManager.GetString("StoreNotICodeBasedEntityStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IEagerLoadingEntityStore&lt;TEntity&gt;..
        /// </summary>
        internal static string StoreNotIEagerLoadingEntityStore {
            get {
                return ResourceManager.GetString("StoreNotIEagerLoadingEntityStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IEntityStore&lt;TEntity&gt;..
        /// </summary>
        internal static string StoreNotIEntityStore {
            get {
                return ResourceManager.GetString("StoreNotIEntityStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IEntityStore&lt;TEntity, TSubEntity&gt;..
        /// </summary>
        internal static string StoreNotIEntityWithSubEntityStore {
            get {
                return ResourceManager.GetString("StoreNotIEntityWithSubEntityStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IExplicitLoadingEntityStore&lt;TEntity&gt;..
        /// </summary>
        internal static string StoreNotIExplicitLoadingEntityStore {
            get {
                return ResourceManager.GetString("StoreNotIExplicitLoadingEntityStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IFilterableEntityStore&lt;TEntity&gt;..
        /// </summary>
        internal static string StoreNotIFilterableEntityStore {
            get {
                return ResourceManager.GetString("StoreNotIFilterableEntityStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IGroupedEntityStore&lt;TEntity, TEntityGroup&gt;..
        /// </summary>
        internal static string StoreNotIGroupedEntityStore {
            get {
                return ResourceManager.GetString("StoreNotIGroupedEntityStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IMasterDetailsEntityStore&lt;TEntity, TEntityDetail&gt;..
        /// </summary>
        internal static string StoreNotIMasterDetailsEntityStore {
            get {
                return ResourceManager.GetString("StoreNotIMasterDetailsEntityStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement INameBasedEntityStore&lt;TEntity&gt;..
        /// </summary>
        internal static string StoreNotINameBasedEntityStore {
            get {
                return ResourceManager.GetString("StoreNotINameBasedEntityStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IQueryableEntityStore&lt;TEntity&gt;..
        /// </summary>
        internal static string StoreNotIQueryableEntityStore {
            get {
                return ResourceManager.GetString("StoreNotIQueryableEntityStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IQueryableEntityStore&lt;TEntity, TSubEntity&gt;..
        /// </summary>
        internal static string StoreNotIQueryableEntityWithSubEntityStore {
            get {
                return ResourceManager.GetString("StoreNotIQueryableEntityWithSubEntityStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IScopedNameBasedEntityStore&lt;TEntity, TEntityScope&gt;..
        /// </summary>
        internal static string StoreNotIScopedNameBasedEntityStore {
            get {
                return ResourceManager.GetString("StoreNotIScopedNameBasedEntityStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement ITimeTrackedEntityStore&lt;TEntity&gt;..
        /// </summary>
        internal static string StoreNotITimeTrackedEntityStore {
            get {
                return ResourceManager.GetString("StoreNotITimeTrackedEntityStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported entity manager for &apos;{0}&apos;. Expected &apos;{1}&apos;, found &apos;{2}&apos;..
        /// </summary>
        internal static string UnsupportedEntityManager {
            get {
                return ResourceManager.GetString("UnsupportedEntityManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should never validates {1}..
        /// </summary>
        internal static string ValidatorNeverValidatesEntity {
            get {
                return ResourceManager.GetString("ValidatorNeverValidatesEntity", resourceCulture);
            }
        }
    }
}
